name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: get FLIR SDK
      run: |
        wget http://cdn.cloud.flir.se/update/SSF/Atlas/1.0.5/Android/thermal-sdk-android-java-1.0.5.tar.gz
        ls
        tar xvzf file.tar.gz thermal-sdk-android-java-1.0.5.tar.gz
        ls
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
