name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get FLIR SDK
      run: |
        wget http://cdn.cloud.flir.se/update/SSF/Atlas/1.0.5/Android/thermal-sdk-android-java-1.0.5.tar.gz
        mkdir SDK
        tar xvzf thermal-sdk-android-java-1.0.5.tar.gz -C SDK
        mkdir app/libs
        cp SDK/thermal-sdk-android-java-1.0.5/thermalsdk-release.aar app/libs/
        cp SDK/thermal-sdk-android-java-1.0.5/androidsdk-release.aar app/libs/
        ls app/libs
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
    - name: Create APK
      run: ./gradlew assembleDebug
    - name: Upload APK artifact
      uses: actions/upload-artifact@master
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk
